org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
android.enableR8.fullMode=false
ksp.useKSP2=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.newDsl=false
